### ISSUE TITLE
Create default project for each user 

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#15]
Each user should have a default project already set up when they first log in called "My First Project". They should have the ability to rename it and add a description etc.

This will ensure users are able to start up a server straight away and start playing around without having to do anything before hand.

**Comment by gweis** [comment]
Not sure how we should tackle this.

Difficulty is, that first login events are unreliable (not even sure whether we can get those). Creating a default project on first attempt to read is usually difficult to implement and would violate the principle that data shouldn't change on a 'read' request.

I would rather suggest to change the workflow here. 
One option I could think of would be to show a shared default project. E.g. a tutorial / getting started project which users can clone and play around with. (sharing / cloning not implemented yet).
Or we change the UI, which just auto creates a new project if none exists, or forces a user to create a new project before anything else can be done.

**Comment by sarahrichmond** [comment]
@gweis I think we should just auto create a new project if none exists, call it 'My first project'.

That way users can log in and immediately get started without having any barriers first.

**Comment by hoylen** [comment]
Now that *all projects* appear under a "Projects" directory in the home directory, does that change things?

Not having any project is no longer a road block to someone launching a server. (I just tested it: deleted all my projects and successfully launched a server). Previously, the design was going to require exactly one project to be available to a server.

We now have a new problem: if the user starts writing files into the `/home/jovyan/Projects` directory, those files are lost when the server is terminated. They have to know (and remember) to write files into a subdirectory of that directory for them to be preserved.

Can we not simply have the single entire _/home/jovyan/Projects_ directory preserved, without making it mandatory to create separate projects? When sharing is implemented, can't users be allowed to share any subdirectory under there (instead of only the top level subdirectory)?

**Comment by hoylen** [comment]
Actually, users are _extremely likely_ to store their notebooks in _/home/jovyan/Projects_ instead of within a proper project (i.e. a subdirectory of it). That is because, by default, that is where JupyterLab is saving the notebooks it creates. So by default, the user is going to loose their notebook they think they have saved.

**Comment by sarahrichmond** [comment]
@gweis I agree with @hoylen. We'll need to fix this somehow. Perhaps adding that default project and ensuring JupyterLab saves to that folder (instead of the over arching /Projects folder will fix it?

This is high priority. Important that users work is saved without too much effort on their end.

**Comment by gweis** [comment]
mmm.... my last comment didn't seem to arrive here....

I am wondering whether we should get rid of the Projects feature entirely and treat the 'drive' section as one large storage. This would make syncing a lot easier, but sharing will be trickier later.

**Comment by gweis** [comment]
Also regarding creating a default project. This is more difficult than it sounds.
1. We don't have yet events from a new user sign up / log in.
2. Creating a default project on first read is also a difficult one, because we modify / create a resource based on a read. This undermines some fundamental assumptions, that a simple read (GET) always does the same, which means, that we have to take care of concurrent read requests. From a transactional point of view, it would be better to create a default project from within the UI and not within the backend service. 

Alternatively we could show an initial example / tutorial project, a user can clone to get started.

**Comment by sarahrichmond** [comment]
Hm, given Projects are meant to only be for code, then perhaps we don't need projects. Make's it a lot easier for users to safely save their scripts.

@hoylen what are your thoughts?

**Comment by hoylen** [comment]
I'm worried that we are going back to calling it "Drive" again :-)

I fully support the idea of having just one big thing, and everything in it is preserved -- it is easier for the user to understand. Easier to document and less the user can get wrong.

Though at the same time we don't want to make sharing difficult for the user to understand and do, or make it too difficult for us to implement.

The requirement for a "default project" is really a requirement to make it easy for the first-time user to explore what ecocloud can do. If their first encounter with ecocloud requires them to first understand what projects are, and create one, before they can launch a server and start playing around, that might put some people off. We expect new users to first want to launch a server to see what ecocloud can do: saving their first test code that does "1+1" and sharing it with others is not something they care about in that first launch. If that can be achieved in another way, then that is fine. Currently, we do have that (they can launch without creating a project), but it does have some big dangers when they eventually do want their code to be persisted.

**Comment by gweis** [comment]
I am not arguing about whether we should have a default project or not. It's probably necessary and should be there.  

With initial 'example / tutorial project' I meant a project curated by us, that has notebooks and documentation about how to use the platform. A user can look at them (not yet implemented) or just clone (not implemented either) it and play around with a curated set of notebooks that explain how things work.

That things outside Projects/ subfolders are not persisted is currently intentional, because we would store files outside of projects, and the UI we have built so far can't deal with these files. (Also another note where that came from is probably, that I was thinking about the Projects/ folder as $HOME folder, and I wanted to avoid persisting ssh keys and other credentials common unit tools store in $HOME.

Maybe we should get together on Wednesday or so and think about how it should look like and how it may work together?

**Comment by sarahrichmond** [comment]
I agree. Lets discuss and whiteboard it out on Wednesday at UQ.

**Comment by hoylen** [comment]
Issue closed: _projects_ have been replaced by a single **workspace**.
