### ISSUE TITLE
Add 'Import Data' menu item to JupyterLab

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#3]
Add an 'Import Data' menu item with a submenu for 'Desktop' and "Dropbox'.

**Comment by hoylen** [comment]
This should create an "Export data" item too -- for moving data _from_ ecocloud out Dropbox etc too.

Consider putting them all under the "File" menu, since that is where the download menu item is already, and where users normally look to do something with files. A "Data transfer" menu might work, but then the "download" menu item is in a separate location (in the File menu) - it would be good if all the file transfer options are in one place.

Currently, in the documentation I'm using the words "download" and "upload" to describe transfers of files between ecocloud and the user's local computer; and "import" and "export" to describe transfers of files between ecocloud and cloud storage outside ecocloud. Happy to change the terms around, but we just need to be consistent throughout.

**Comment by gweis** [comment]
This is implemented and deployed. I suggest we track any UI/UX changes in a new ticket.
