### ISSUE TITLE
Changes to Projects/Workspace

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#42]
- [x] Rename Projects to Workspace
- [x] Remove folder structure and 'Add Project' button
- [x] Have Workspace page show all files/list of files.

**Comment by manhinli** [comment]
Currently have got changes filed in a PR that renames references to "ecocloud Projects" into "ecocloud Workspace", however the actual usage and layout is the same and I have not yet removed the component that lists the available projects.

Things like "Add/delete project(s)" buttons are still present because the fundamental structure of it has not changed and this will require work:
* default, single project for all users? or will there no longer be the concept of "projects" in the background?
* API may need to be updated

**Comment by gweis** [comment]
all done
