### ISSUE TITLE
Switch layout of log in page

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#43]
Switch the layout of the log in page to show AAF first with header 'Log in using your University ID'

And then have a section below this that says 'Log in with another account' and show Google and local account.

This will hopefully encourage those that have AAF log ins to use that instead of Google or local accounts.

**Comment by hoylen** [comment]
`s/log in/sign in/ig`

**Comment by manhinli** [comment]
It seems that AAF and Google account sign in are all considered the same type of login by Keycloak - an external third party provider (which it technically is) - so there's no nice way of breaking that into two groups unless I go and make an explicit "name === 'AAF' -> go here" sort of filter.

**Comment by hoylen** [comment]
With the appropriate CSS selectors, you can probably target the AAF button and move everything on the page around (without needing to change the page structure that Keycloak generates). Probably not for the alpha release, since it will take a lot of time to get right.

Any chance the ecocloud/local login's email address and password fields can be made smaller and/or moved around on the page (so the AAF button is the first one they see)?

**Comment by manhinli** [comment]
At the moment I have it split with two regions stacked vertically, so I'll probably press ahead and finish to roughly what we had envisaged the other day.

![image](https://user-images.githubusercontent.com/3337903/44962346-0fb55d00-af62-11e8-9078-b4bca17d8acc.png)

**Comment by hoylen** [comment]
Perfect.

**Comment by manhinli** [comment]
What I have now is this, with the local account form hidden by default, and toggled by the "Sign in with ecocloud" button.

![image](https://user-images.githubusercontent.com/3337903/44962810-9705cf00-af68-11e8-8ab3-ecc0f9737a22.png)

**Comment by hoylen** [comment]
That is beautiful.

I assume the "New user? Register" only appears when the "Sign in with ecocloud" reveals the ecocloud Account options.

The heading: "ecocloud Account" vs "ecocloud login"? See thoughts about this in https://github.com/ausecocloud/ecocloud/issues/46

**Comment by manhinli** [comment]
> I assume the "New user? Register" only appears when the "Sign in with ecocloud" reveals the ecocloud Account options.

Not by default - and not at the moment either, because if you do end up hiding it then people who don't have an account at any of the services listed would be absolutely lost.

I'm thinking of changing the wording entirely to something like "Don't have any of the above accounts? Register for an ecocloud account".

**Comment by hoylen** [comment]
That makes sense.

The rewording is great. I was worried that people with AAF and/or Google might think they still need to register.

**Comment by manhinli** [comment]
Here's a shot of the collapsed state of the form with the new wording and my suggestion to use "ecocloud ID" from #46.

![image](https://user-images.githubusercontent.com/3337903/44963402-86a42300-af6d-11e8-991a-b6f7b4b3b0c0.png)

**Comment by hoylen** [comment]
How about "Sign in using another ID" and "Do not have any of the above IDs?" -- that will perfectly satisfy my concern about the overloading the word "account".

**Comment by manhinli** [comment]
"Do not have any of the above IDs" sounds really stiff. Would "don't" be acceptable?

**Comment by hoylen** [comment]
Yes, "don't" is fine :-)

**Comment by manhinli** [comment]
Done.

**Comment by gweis** [comment]
deployed
