### ISSUE TITLE
Hide signing in with a local login on app.ecocloud.org.au

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#7]
For the alpha release we will only allow users to log in through AAF. Need to remove the 'local account' login option from the UI.

**Comment by hoylen** [comment]
And use the term "**sign in**" throughout the platform (replacing "login" and "log in"). We need to be consistent.

It occurs in these places, perhaps other places too:

- On the "Log in to ecocloud" page it occurs in the page title, heading, text and buttons.
- On the "Your are not logged in" page it occurs in three places. But issue https://github.com/ausecocloud/ecocloud/issues/16 should mean that page is never seen again.
- After signing in, the menu item under your name should be "Sign out" instead of "Logout".

The AAF button should be capitalised "Sign in with AAF" (lowercase "I" and "W").

**Comment by manhinli** [comment]
Some of the suggestions regarding use of the term "sign in" rather than "login" and other small textual changes has been incorporated into various parts already.
I would say that since we are trying to enable local sign in again in #34, that you can close this.
